import "@/app/globals.css";
import { Open_Sans } from "next/font/google";
import Providers from "@/app/providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-opensans",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} bg-bggray [&>*]:px-4 [&>*]:sm:px-24 [&>*]:md:px-36 [&>*]:lg:px-52 [&>*]:xl:px-80`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
